<?php

use Illuminate\Database\Seeder;

class DataRowsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('data_rows')->delete();
        
        \DB::table('data_rows')->insert(array (
            0 => 
            array (
                'id' => 1,
                'data_type_id' => 1,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            1 => 
            array (
                'id' => 2,
                'data_type_id' => 1,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            2 => 
            array (
                'id' => 3,
                'data_type_id' => 1,
                'field' => 'email',
                'type' => 'text',
                'display_name' => 'Email',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 3,
            ),
            3 => 
            array (
                'id' => 4,
                'data_type_id' => 1,
                'field' => 'password',
                'type' => 'password',
                'display_name' => 'Password',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => NULL,
                'order' => 4,
            ),
            4 => 
            array (
                'id' => 5,
                'data_type_id' => 1,
                'field' => 'remember_token',
                'type' => 'text',
                'display_name' => 'Remember Token',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 5,
            ),
            5 => 
            array (
                'id' => 6,
                'data_type_id' => 1,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 6,
            ),
            6 => 
            array (
                'id' => 7,
                'data_type_id' => 1,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 7,
            ),
            7 => 
            array (
                'id' => 8,
                'data_type_id' => 1,
                'field' => 'avatar',
                'type' => 'image',
                'display_name' => 'Avatar',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 8,
            ),
            8 => 
            array (
                'id' => 9,
                'data_type_id' => 1,
                'field' => 'user_belongsto_role_relationship',
                'type' => 'relationship',
                'display_name' => 'Role',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsTo","column":"role_id","key":"id","label":"display_name","pivot_table":"roles","pivot":0}',
                'order' => 10,
            ),
            9 => 
            array (
                'id' => 10,
                'data_type_id' => 1,
                'field' => 'user_belongstomany_role_relationship',
                'type' => 'relationship',
                'display_name' => 'Roles',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsToMany","column":"id","key":"id","label":"display_name","pivot_table":"user_roles","pivot":"1","taggable":"0"}',
                'order' => 11,
            ),
            10 => 
            array (
                'id' => 11,
                'data_type_id' => 1,
                'field' => 'settings',
                'type' => 'hidden',
                'display_name' => 'Settings',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 12,
            ),
            11 => 
            array (
                'id' => 12,
                'data_type_id' => 2,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            12 => 
            array (
                'id' => 13,
                'data_type_id' => 2,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            13 => 
            array (
                'id' => 14,
                'data_type_id' => 2,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 3,
            ),
            14 => 
            array (
                'id' => 15,
                'data_type_id' => 2,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 4,
            ),
            15 => 
            array (
                'id' => 16,
                'data_type_id' => 3,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            16 => 
            array (
                'id' => 17,
                'data_type_id' => 3,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            17 => 
            array (
                'id' => 18,
                'data_type_id' => 3,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 3,
            ),
            18 => 
            array (
                'id' => 19,
                'data_type_id' => 3,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 4,
            ),
            19 => 
            array (
                'id' => 20,
                'data_type_id' => 3,
                'field' => 'display_name',
                'type' => 'text',
                'display_name' => 'Display Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 5,
            ),
            20 => 
            array (
                'id' => 21,
                'data_type_id' => 1,
                'field' => 'role_id',
                'type' => 'text',
                'display_name' => 'Role',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 9,
            ),
            21 => 
            array (
                'id' => 22,
                'data_type_id' => 5,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            22 => 
            array (
                'id' => 23,
                'data_type_id' => 5,
                'field' => 'banner_text',
                'type' => 'rich_text_box',
                'display_name' => 'Banner Text',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            23 => 
            array (
                'id' => 24,
                'data_type_id' => 5,
                'field' => 'confiance_text',
                'type' => 'rich_text_box',
                'display_name' => 'Confiance Text',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            24 => 
            array (
                'id' => 25,
                'data_type_id' => 5,
                'field' => 'tab1_text',
                'type' => 'rich_text_box',
                'display_name' => 'Tab1 Text',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 4,
            ),
            25 => 
            array (
                'id' => 26,
                'data_type_id' => 5,
                'field' => 'tab2_text',
                'type' => 'rich_text_box',
                'display_name' => 'Tab2 Text',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 5,
            ),
            26 => 
            array (
                'id' => 27,
                'data_type_id' => 5,
                'field' => 'tab3_text',
                'type' => 'rich_text_box',
                'display_name' => 'Tab3 Text',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 6,
            ),
            27 => 
            array (
                'id' => 28,
                'data_type_id' => 5,
                'field' => 'tab4_text',
                'type' => 'rich_text_box',
                'display_name' => 'Tab4 Text',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 7,
            ),
            28 => 
            array (
                'id' => 29,
                'data_type_id' => 5,
                'field' => 'tab5_text',
                'type' => 'rich_text_box',
                'display_name' => 'Tab5 Text',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 8,
            ),
            29 => 
            array (
                'id' => 30,
                'data_type_id' => 5,
                'field' => 'tab6_text',
                'type' => 'rich_text_box',
                'display_name' => 'Tab6 Text',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 9,
            ),
            30 => 
            array (
                'id' => 31,
                'data_type_id' => 5,
                'field' => 'tab1_img',
                'type' => 'image',
                'display_name' => 'Tab1 Img',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 10,
            ),
            31 => 
            array (
                'id' => 32,
                'data_type_id' => 5,
                'field' => 'tab2_img',
                'type' => 'image',
                'display_name' => 'Tab2 Img',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 11,
            ),
            32 => 
            array (
                'id' => 33,
                'data_type_id' => 5,
                'field' => 'tab3_img',
                'type' => 'image',
                'display_name' => 'Tab3 Img',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 12,
            ),
            33 => 
            array (
                'id' => 34,
                'data_type_id' => 5,
                'field' => 'tab4_img',
                'type' => 'image',
                'display_name' => 'Tab4 Img',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 13,
            ),
            34 => 
            array (
                'id' => 35,
                'data_type_id' => 5,
                'field' => 'tab5_img',
                'type' => 'image',
                'display_name' => 'Tab5 Img',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 14,
            ),
            35 => 
            array (
                'id' => 36,
                'data_type_id' => 5,
                'field' => 'tab6_img',
                'type' => 'image',
                'display_name' => 'Tab6 Img',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 15,
            ),
            36 => 
            array (
                'id' => 37,
                'data_type_id' => 5,
                'field' => 'connexion_text',
                'type' => 'rich_text_box',
                'display_name' => 'Connexion Text',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 16,
            ),
            37 => 
            array (
                'id' => 38,
                'data_type_id' => 5,
                'field' => 'demo_text',
                'type' => 'text',
                'display_name' => 'Demo Text',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 17,
            ),
            38 => 
            array (
                'id' => 39,
                'data_type_id' => 5,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '{}',
                'order' => 18,
            ),
            39 => 
            array (
                'id' => 40,
                'data_type_id' => 5,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 19,
            ),
            40 => 
            array (
                'id' => 41,
                'data_type_id' => 7,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            41 => 
            array (
                'id' => 42,
                'data_type_id' => 7,
                'field' => 'title',
                'type' => 'text',
                'display_name' => 'Title',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            42 => 
            array (
                'id' => 43,
                'data_type_id' => 7,
                'field' => 'banner_texte',
                'type' => 'rich_text_box',
                'display_name' => 'Banner Texte',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            43 => 
            array (
                'id' => 44,
                'data_type_id' => 7,
                'field' => 'carac1_title',
                'type' => 'text',
                'display_name' => 'Carac1 Title',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 4,
            ),
            44 => 
            array (
                'id' => 45,
                'data_type_id' => 7,
                'field' => 'carac1_content',
                'type' => 'text',
                'display_name' => 'Carac1 Content',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 5,
            ),
            45 => 
            array (
                'id' => 46,
                'data_type_id' => 7,
                'field' => 'carac2_title',
                'type' => 'text',
                'display_name' => 'Carac2 Title',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 6,
            ),
            46 => 
            array (
                'id' => 47,
                'data_type_id' => 7,
                'field' => 'carac2_content',
                'type' => 'text',
                'display_name' => 'Carac2 Content',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 7,
            ),
            47 => 
            array (
                'id' => 48,
                'data_type_id' => 7,
                'field' => 'carac3_title',
                'type' => 'text',
                'display_name' => 'Carac3 Title',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 8,
            ),
            48 => 
            array (
                'id' => 49,
                'data_type_id' => 7,
                'field' => 'carac3_content',
                'type' => 'text',
                'display_name' => 'Carac3 Content',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 9,
            ),
            49 => 
            array (
                'id' => 50,
                'data_type_id' => 7,
                'field' => 'carac4_title',
                'type' => 'text',
                'display_name' => 'Carac4 Title',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 10,
            ),
            50 => 
            array (
                'id' => 51,
                'data_type_id' => 7,
                'field' => 'carac4_content',
                'type' => 'text',
                'display_name' => 'Carac4 Content',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 11,
            ),
            51 => 
            array (
                'id' => 52,
                'data_type_id' => 7,
                'field' => 'carac5_title',
                'type' => 'text',
                'display_name' => 'Carac5 Title',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 12,
            ),
            52 => 
            array (
                'id' => 53,
                'data_type_id' => 7,
                'field' => 'carac5_content',
                'type' => 'text',
                'display_name' => 'Carac5 Content',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 13,
            ),
            53 => 
            array (
                'id' => 54,
                'data_type_id' => 7,
                'field' => 'carac6_title',
                'type' => 'text',
                'display_name' => 'Carac6 Title',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 14,
            ),
            54 => 
            array (
                'id' => 55,
                'data_type_id' => 7,
                'field' => 'carac6_content',
                'type' => 'text',
                'display_name' => 'Carac6 Content',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 15,
            ),
            55 => 
            array (
                'id' => 56,
                'data_type_id' => 7,
                'field' => 'carac7_title',
                'type' => 'text',
                'display_name' => 'Carac7 Title',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 16,
            ),
            56 => 
            array (
                'id' => 57,
                'data_type_id' => 7,
                'field' => 'carac7_content',
                'type' => 'text',
                'display_name' => 'Carac7 Content',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 17,
            ),
            57 => 
            array (
                'id' => 58,
                'data_type_id' => 7,
                'field' => 'carac8_title',
                'type' => 'text',
                'display_name' => 'Carac8 Title',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 18,
            ),
            58 => 
            array (
                'id' => 59,
                'data_type_id' => 7,
                'field' => 'carac8_content',
                'type' => 'text',
                'display_name' => 'Carac8 Content',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 19,
            ),
            59 => 
            array (
                'id' => 60,
                'data_type_id' => 7,
                'field' => 'carac9_title',
                'type' => 'text',
                'display_name' => 'Carac9 Title',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 20,
            ),
            60 => 
            array (
                'id' => 61,
                'data_type_id' => 7,
                'field' => 'carac9_content',
                'type' => 'text',
                'display_name' => 'Carac9 Content',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 21,
            ),
            61 => 
            array (
                'id' => 62,
                'data_type_id' => 7,
                'field' => 'carac10_title',
                'type' => 'text',
                'display_name' => 'Carac10 Title',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 22,
            ),
            62 => 
            array (
                'id' => 63,
                'data_type_id' => 7,
                'field' => 'carac10_content',
                'type' => 'text',
                'display_name' => 'Carac10 Content',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 23,
            ),
            63 => 
            array (
                'id' => 64,
                'data_type_id' => 7,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '{}',
                'order' => 24,
            ),
            64 => 
            array (
                'id' => 65,
                'data_type_id' => 7,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 25,
            ),
            65 => 
            array (
                'id' => 66,
                'data_type_id' => 9,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            66 => 
            array (
                'id' => 67,
                'data_type_id' => 9,
                'field' => 'title',
                'type' => 'text',
                'display_name' => 'Title',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            67 => 
            array (
                'id' => 68,
                'data_type_id' => 9,
                'field' => 'intro',
                'type' => 'text',
                'display_name' => 'Intro',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            68 => 
            array (
                'id' => 69,
                'data_type_id' => 9,
                'field' => 'fct1_text',
                'type' => 'rich_text_box',
                'display_name' => 'Fct1 Text',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 4,
            ),
            69 => 
            array (
                'id' => 70,
                'data_type_id' => 9,
                'field' => 'fct1_title',
                'type' => 'text',
                'display_name' => 'Fct1 Title',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 5,
            ),
            70 => 
            array (
                'id' => 71,
                'data_type_id' => 9,
                'field' => 'fct1_img',
                'type' => 'image',
                'display_name' => 'Fct1 Img',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 6,
            ),
            71 => 
            array (
                'id' => 72,
                'data_type_id' => 9,
                'field' => 'fct2_text',
                'type' => 'rich_text_box',
                'display_name' => 'Fct2 Text',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 7,
            ),
            72 => 
            array (
                'id' => 73,
                'data_type_id' => 9,
                'field' => 'fct2_title',
                'type' => 'text',
                'display_name' => 'Fct2 Title',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 8,
            ),
            73 => 
            array (
                'id' => 74,
                'data_type_id' => 9,
                'field' => 'fct2_img',
                'type' => 'image',
                'display_name' => 'Fct2 Img',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 9,
            ),
            74 => 
            array (
                'id' => 75,
                'data_type_id' => 9,
                'field' => 'fct3_text',
                'type' => 'rich_text_box',
                'display_name' => 'Fct3 Text',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 10,
            ),
            75 => 
            array (
                'id' => 76,
                'data_type_id' => 9,
                'field' => 'fct3_title',
                'type' => 'text',
                'display_name' => 'Fct3 Title',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 11,
            ),
            76 => 
            array (
                'id' => 77,
                'data_type_id' => 9,
                'field' => 'fct3_img',
                'type' => 'image',
                'display_name' => 'Fct3 Img',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 12,
            ),
            77 => 
            array (
                'id' => 78,
                'data_type_id' => 9,
                'field' => 'fct4_text',
                'type' => 'rich_text_box',
                'display_name' => 'Fct4 Text',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 13,
            ),
            78 => 
            array (
                'id' => 79,
                'data_type_id' => 9,
                'field' => 'fct4_title',
                'type' => 'text',
                'display_name' => 'Fct4 Title',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 14,
            ),
            79 => 
            array (
                'id' => 80,
                'data_type_id' => 9,
                'field' => 'fct4_img',
                'type' => 'image',
                'display_name' => 'Fct4 Img',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 15,
            ),
            80 => 
            array (
                'id' => 81,
                'data_type_id' => 9,
                'field' => 'fct5_text',
                'type' => 'rich_text_box',
                'display_name' => 'Fct5 Text',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 16,
            ),
            81 => 
            array (
                'id' => 82,
                'data_type_id' => 9,
                'field' => 'fct5_title',
                'type' => 'text',
                'display_name' => 'Fct5 Title',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 17,
            ),
            82 => 
            array (
                'id' => 83,
                'data_type_id' => 9,
                'field' => 'fct5_img',
                'type' => 'image',
                'display_name' => 'Fct5 Img',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 18,
            ),
            83 => 
            array (
                'id' => 84,
                'data_type_id' => 9,
                'field' => 'fct6_text',
                'type' => 'rich_text_box',
                'display_name' => 'Fct6 Text',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 19,
            ),
            84 => 
            array (
                'id' => 85,
                'data_type_id' => 9,
                'field' => 'fct6_title',
                'type' => 'text',
                'display_name' => 'Fct6 Title',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 20,
            ),
            85 => 
            array (
                'id' => 86,
                'data_type_id' => 9,
                'field' => 'fct6_img',
                'type' => 'image',
                'display_name' => 'Fct6 Img',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 21,
            ),
            86 => 
            array (
                'id' => 87,
                'data_type_id' => 9,
                'field' => 'fct7_text',
                'type' => 'rich_text_box',
                'display_name' => 'Fct7 Text',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 22,
            ),
            87 => 
            array (
                'id' => 88,
                'data_type_id' => 9,
                'field' => 'fct7_title',
                'type' => 'text',
                'display_name' => 'Fct7 Title',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 23,
            ),
            88 => 
            array (
                'id' => 89,
                'data_type_id' => 9,
                'field' => 'fct7_img',
                'type' => 'image',
                'display_name' => 'Fct7 Img',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 24,
            ),
            89 => 
            array (
                'id' => 90,
                'data_type_id' => 9,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '{}',
                'order' => 25,
            ),
            90 => 
            array (
                'id' => 91,
                'data_type_id' => 9,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 26,
            ),
            91 => 
            array (
                'id' => 92,
                'data_type_id' => 10,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            92 => 
            array (
                'id' => 93,
                'data_type_id' => 10,
                'field' => 'slug',
                'type' => 'text',
                'display_name' => 'Slug',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            93 => 
            array (
                'id' => 94,
                'data_type_id' => 10,
                'field' => 'title',
                'type' => 'text',
                'display_name' => 'Title',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            94 => 
            array (
                'id' => 95,
                'data_type_id' => 10,
                'field' => 'intro',
                'type' => 'rich_text_box',
                'display_name' => 'Intro',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 4,
            ),
            95 => 
            array (
                'id' => 96,
                'data_type_id' => 10,
                'field' => 'text_btn',
                'type' => 'text',
                'display_name' => 'Text Btn',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 5,
            ),
            96 => 
            array (
                'id' => 97,
                'data_type_id' => 10,
                'field' => 'title_1',
                'type' => 'text',
                'display_name' => 'Title 1',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 6,
            ),
            97 => 
            array (
                'id' => 98,
                'data_type_id' => 10,
                'field' => 'contenu_1',
                'type' => 'rich_text_box',
                'display_name' => 'Contenu 1',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 7,
            ),
            98 => 
            array (
                'id' => 99,
                'data_type_id' => 10,
                'field' => 'img_1',
                'type' => 'image',
                'display_name' => 'Img 1',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 8,
            ),
            99 => 
            array (
                'id' => 100,
                'data_type_id' => 10,
                'field' => 'title_2',
                'type' => 'text',
                'display_name' => 'Title 2',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 9,
            ),
            100 => 
            array (
                'id' => 101,
                'data_type_id' => 10,
                'field' => 'contenu_2',
                'type' => 'rich_text_box',
                'display_name' => 'Contenu 2',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 10,
            ),
            101 => 
            array (
                'id' => 102,
                'data_type_id' => 10,
                'field' => 'img_2',
                'type' => 'image',
                'display_name' => 'Img 2',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 11,
            ),
            102 => 
            array (
                'id' => 103,
                'data_type_id' => 10,
                'field' => 'title_3',
                'type' => 'text',
                'display_name' => 'Title 3',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 12,
            ),
            103 => 
            array (
                'id' => 104,
                'data_type_id' => 10,
                'field' => 'contenu_3',
                'type' => 'rich_text_box',
                'display_name' => 'Contenu 3',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 13,
            ),
            104 => 
            array (
                'id' => 105,
                'data_type_id' => 10,
                'field' => 'img_3',
                'type' => 'image',
                'display_name' => 'Img 3',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 14,
            ),
            105 => 
            array (
                'id' => 106,
                'data_type_id' => 10,
                'field' => 'title_4',
                'type' => 'text',
                'display_name' => 'Title 4',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 15,
            ),
            106 => 
            array (
                'id' => 107,
                'data_type_id' => 10,
                'field' => 'contenu_4',
                'type' => 'rich_text_box',
                'display_name' => 'Contenu 4',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 16,
            ),
            107 => 
            array (
                'id' => 108,
                'data_type_id' => 10,
                'field' => 'img_4',
                'type' => 'image',
                'display_name' => 'Img 4',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 17,
            ),
            108 => 
            array (
                'id' => 109,
                'data_type_id' => 10,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '{}',
                'order' => 18,
            ),
            109 => 
            array (
                'id' => 110,
                'data_type_id' => 10,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 19,
            ),
            110 => 
            array (
                'id' => 111,
                'data_type_id' => 9,
                'field' => 'fct8_text',
                'type' => 'rich_text_box',
                'display_name' => 'Fct8 Text',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 27,
            ),
            111 => 
            array (
                'id' => 112,
                'data_type_id' => 9,
                'field' => 'fct8_title',
                'type' => 'text',
                'display_name' => 'Fct8 Title',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 28,
            ),
            112 => 
            array (
                'id' => 113,
                'data_type_id' => 9,
                'field' => 'fct8_img',
                'type' => 'image',
                'display_name' => 'Fct8 Img',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 29,
            ),
            113 => 
            array (
                'id' => 114,
                'data_type_id' => 9,
                'field' => 'fct9_text',
                'type' => 'rich_text_box',
                'display_name' => 'Fct9 Text',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 30,
            ),
            114 => 
            array (
                'id' => 115,
                'data_type_id' => 9,
                'field' => 'fct9_title',
                'type' => 'text',
                'display_name' => 'Fct9 Title',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 31,
            ),
            115 => 
            array (
                'id' => 116,
                'data_type_id' => 9,
                'field' => 'fct9_img',
                'type' => 'image',
                'display_name' => 'Fct9 Img',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 32,
            ),
            116 => 
            array (
                'id' => 117,
                'data_type_id' => 9,
                'field' => 'fct10_text',
                'type' => 'rich_text_box',
                'display_name' => 'Fct10 Text',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 33,
            ),
            117 => 
            array (
                'id' => 118,
                'data_type_id' => 9,
                'field' => 'fct10_title',
                'type' => 'text',
                'display_name' => 'Fct10 Title',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 34,
            ),
            118 => 
            array (
                'id' => 119,
                'data_type_id' => 9,
                'field' => 'fct10_img',
                'type' => 'image',
                'display_name' => 'Fct10 Img',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 35,
            ),
            119 => 
            array (
                'id' => 120,
                'data_type_id' => 9,
                'field' => 'fct11_text',
                'type' => 'rich_text_box',
                'display_name' => 'Fct11 Text',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 36,
            ),
            120 => 
            array (
                'id' => 121,
                'data_type_id' => 9,
                'field' => 'fct11_title',
                'type' => 'text',
                'display_name' => 'Fct11 Title',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 37,
            ),
            121 => 
            array (
                'id' => 122,
                'data_type_id' => 9,
                'field' => 'fct11_img',
                'type' => 'image',
                'display_name' => 'Fct11 Img',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 38,
            ),
            122 => 
            array (
                'id' => 123,
                'data_type_id' => 9,
                'field' => 'fct12_text',
                'type' => 'rich_text_box',
                'display_name' => 'Fct12 Text',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 39,
            ),
            123 => 
            array (
                'id' => 124,
                'data_type_id' => 9,
                'field' => 'fct12_title',
                'type' => 'text',
                'display_name' => 'Fct12 Title',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 40,
            ),
            124 => 
            array (
                'id' => 125,
                'data_type_id' => 9,
                'field' => 'fct12_img',
                'type' => 'image',
                'display_name' => 'Fct12 Img',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 41,
            ),
            125 => 
            array (
                'id' => 126,
                'data_type_id' => 7,
                'field' => 'main_img',
                'type' => 'image',
                'display_name' => 'Main Img',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 26,
            ),
        ));
        
        
    }
}